### ISSUE TITLE
Blog: listening to soundscapes

### ISSUE THREAD

**Issue by benmiller314** [pitt-cdm/miller2019spring#3]
After completing the reading and listening portions of the homework after lesson 03, come here and record a few thoughts. What do you notice, i.e. what stands out while reading or listening? What does that suggest, or what does it make you wonder?

As always in blog posts, responding to each other is optional but encouraged: you can use the @ symbol to mention someone by name, and they'll receive a notification.

**Comment by tessasayers** [comment]
I really liked the student soundscapes and I thought the different takes they had were really interesting. I also realized how important it is to pay attention to the little details, in "Day in, Day out" you were able to follow along because of how smoothly everything flowed and the little details. I also they were really good examples of how you can accomplish the same things with and without speaking, but having voices to break up the noise was a really good technique. As for myself, I am worried about how to overlap sounds and reach the required time without making it seem too redundant. 
I am really going to try to focus on development and uniqueness, because those were things I picked up from the readings and thing that stood out to me in the clips I listened to. 
One question I have is, is it ok to have some white or quiet space? Should everything have some sound at all times, or does some quiet help to build the scene?

**Comment by christyh310** [comment]
I think the tip on the 'development' aspect of great recordings and then the note on the _people_ being the place are both really interesting and were helpful in how I can think about this project. 

At first, when I read over the 'development' section of the first article, though, I thought that perhaps the soundclip in one place needed to be so engaging that it could create the story for itself, but I realized after listening to the students' soundscapes that they could create the development of their own sound clips, through a combination of surrounding sounds, sounds in their apartments, etc. This is helpful, because I know that a long, all-encompassing sound-clip does not have to be a part of my soundscape, necessarily. 

I really appreciate the note that the _people_ are the place because this is what I notice when I am walking, studying, or intentionally meeting with someone on campus or elsewhere. It's the people, their movements, thoughts, conversations, and reactions that fuel the sounds of the place. They are also what makes the soundclip grounded (more relatable). I intend to use a variety of people's voices in my soundclip, for this reason, and perhaps in the background of the soundscape, because I realize that human voices are extraordinary in their ability to bring a certain place/feeling to life.

**Comment by jennyaimei120** [comment]
Last semester I took a music class, and the professor then introduced a soundscape project. In that class I had no idea what it was, or understood it at all. Now that I've completed that class I have a good understanding on what a soundscape _is_ . When you go around your normal routine you don't really listen to your surroundings. Once you take your headphones out, you can really focus on the things around you. You hear the cars, birds and the laughter on the streets of friends.  The different soundscapes from students represented them, they were different and unique.

**Comment by jfrank1120** [comment]
The biggest take away I had from listening to previous students is the use of background sounds to create the ambiance for whatever scene they are setting. Especially in the soundscapes that were set in atmosphere's such as space, the background tracks tended to keep reminding me of where it was taking place even when there was no direct dialog. 

Another aspect of all of the soundscapes that I noticed was the changing of volume of certain sounds in order to bring them to the attention of the listener. Whether it was speaking tracks conveying information, or events that were occurring in the background, they all seemed to understand how to draw the listeners attention quite well.

The final thing that stuck out to me was that the overlaying of sounds did not actually sound as bad as I thought it could. On the rubric when it requires 4 sounds at once, I was afraid that the soundscape would get too muddied by multiple tracks, let alone 4. However, all of the examples did a good job overlaying the sounds without taking away from each other or overloading the listener.

**Comment by dashn98** [comment]
When reading the passages, one thing that really stood out to me is how they discussed recordings should tell a story that people can understand but also surprises them. I think it is interesting how noises are associated with certain tasks and how a certain combination of noises can catch your attention if they are unexpected. When I was listening to the Breaking Bad intro what stood out to me was the higher pitched ring that happened about two thirds into the recording. I couldn’t quite tell what this sound was or its meaning, but it very much so contrasted with the previous sounds allowing whatever it represented to stand out. The student pieces were very interesting and sparked some inspiration and thought about the sounds that I hear each day and how they might be pieced together to tell a specific story. This is a very different and interesting type of media and will be cool to explore the ways that sound can be pieced together and overlapped to create a story.

**Comment by laurasosovicka** [comment]
I really enjoyed listening to the examples, as they gave me a taste of what is expected from the assignment. At first, I was a little bit concerned when hearing we needed to layer 4 sounds at once. I thought that seemed overwhelming to the ear. Once I listened to the examples, I noticed how well the sounds complimented one another and were able to tell a story. Even ones that had only sounds made you feel as if you were actively there at the scene. During the sounds with voices, I would close my eyes and imagine myself being there in person listening and seeing everything featured. 

The readings were helpful in giving good pointers on how to engage a listener. Moving around and picking up on sounds can be timed perfectly to make the soundscape come together. Also, your ears perceive sound differently than your recording device does. So the way you hear things could be different from how your phone hears things. 

The student excerpts gave me inspiration for my soundscape. The "Day In Day Out" soundscape was highly relatable because it sounded as if the person was going through their daily routine. Each one used sounds we hear every day, which made me think more about how to incorporate certain sounds around me. One thing that stood out was how some soundscapes would pause for a brief moment before emphasizing a specific sound. I liked how they used suspense to keep the listener wondering what was going to happen next.

**Comment by mpalko** [comment]
What stuck out to me the most is the idea that our everyday lives create the sounds we hear. And often, because it is so frequent, we don't really think about it. When the sounds from the Leicester Market played, I was fascinated. I could imagine myself walking around and hearing those people because they were non-typical sounds which made me think of a non-typical experience. 

Juxtaposing that, I felt a familiarity when the "Day In Day Out" soundscape played. I recognized the typical running of the shower, the annoying alarm, and the noisy, city traffic. These are sounds I hear everyday, and I experience them without even giving them a thought. It was interesting to reflect back on these typical sounds and realize how they could be transformed into something meaningful and relatable. 

Going off the idea of transformation, it also surprised me to hear The Cat in the Hat in such an eerie manner. Having the idea to change a children's book into what sounds like a nightmare was creepy but also very thoughtful and impressive. A lot of times, we get used to a sound and always picture it the way we have heard it, but this showed me that any reading is changeable by different sounds.

**Comment by bcy5** [comment]
I think the most important lesson that I learned from listening to the audio files and completing the reading is that noise alone can easily tell a story. I found it interesting that in one of the readings, they emphasized the "Sense of a place". They explained that even though it is very simple to record the noise from a busy street, each sound has an identity of their own. For example, the audio clip of Leicester Market is unique because of the ambiance of sound that includes unique East Midlands accents.

Also, another example of "Sense of a place" can be heard in two of the students' recordings. The two very similar recordings about space travel and their encounter with extraterrestrial beings were of a very similar topic, but were also very different because of how the creator decided to manipulate the story telling aspect by using different types of audio files.

**Comment by eaj34** [comment]
Going into this assignment I tried to imagine what kind of things I could do with it and was having difficulties imagining a world to recreate. After the readings and the examples, I felt a little bit better because I never realized, until now, how much sound and noise there is in our lives. There was also a moment where I was amazed about how we don't really need words to tell a story. 

Listening to "Still Hungry in America," I closed my eyes as the text recommended and I was baffled at how right they were. I was able to picture this people talk about their lives and homes. It really broke the scenes of their lives into my world. 

Regarding the examples, like most people who posted before me, "Day In, Day Out" was a soundscape that stuck with me because I felt that it related with my past summer. I would have a routine of when I worked and did things and there was no special days, just every day the same. The sounds were able to tell a story with him saying anything. I loved it! And you could really imagine this student going through the motions of life that seem so mundane.

**Comment by jlherrle** [comment]
I really liked this assignment and taking the time to listen to all of the sounds that we hear, but never really notice. Noises tell a lot about what it going on. For example, if you hear loud car horns and the commotion of people you may interpret that the noises are taking place at rush hour in a busy city. While on the other hand, hearing birds chirping and crickets can easily mean that you are listening to the noises of a forest. 

I think we neglect to notice how often we use noises to interpret what is happening around us. We take advantage of being able to hear the world around us without noticing really how much you can pick up from what you are listening to. In the cities and memory article I liked the section uniqueness. I like how they mentioned that the same place can sound totally different depending on the time of day. As I mentioned early, a city may sound different during rush hour in the morning then midnight. Noises around us are constantly changing and we never really realize it.

**Comment by tyllerbarner** [comment]
This assignment really helped me to better get an understanding of how I would like to approach my soundscape project. I was having a hard time coming up with something to do, but after listening to the examples and reading the articles I feel as though I have a better understanding of how to approach the assignment and how I would like to create my project. 

Something that really grabbed my attention was from the "6 NPR stories that breathe life into neighborhood scenes." When the author mentioned that the people are the place, I really found this point to be important since when I first started thinking of this assignment, I only thought of what sounds I should try and capture, and not so much people's voices. I also enjoyed listening to the Cat in the Hat excerpt project. I think that this student project in particular helped me to better understand how just sounds working together can create a particular mood, which helped me to better get an understanding of what I wanted to create and what story I wanted to tell.

**Comment by jlt118** [comment]
Listening to the different soundscape narratives, I was able to gain a better understanding of what this assignment could entail. The emotional reactions connected to certain sounds stood out to me as a driving force for creating these narratives. The "day in, day out" narrative was very relatable to the patterned lives we lead. While every day may not be the exact same, the noises imitating our routine are consistent. Noises can provide location, context, and emotion that are all vital parts to a story, whether or not words are involved. I think that after listening to these telling a simple but effective story is my goal, without clogging the soundscape with too many overlapping noises and having a clear purpose.

**Comment by esc37** [comment]
I enjoyed listening to the different soundscape narratives, and seeing how different people interpreted the assignment. I enjoyed how some people used the assignment to express how they felt about life, and their concerns for the future, while others used it to construct fictional stories, showcasing their vivid imaginations. Through listening to others' soundscape narratives, I was able to reinterpret my own plan for my soundscape, and reevaluate what I wanted my soundscape to convey. I also enjoyed that all the others included voices and layered other sounds to further enhance their soundscape. Additionally, after reading and listening to the two links that were provided, "Illustrating the Unexpected" stood out to me the most. I personally would assume that people listening to the audio would not be able to visualize the scenery or story if it wasn't something that they expected, but instead I enjoyed and understood how the author was able to depict the scenery by inserting something that people would not expect but also relate to.

**Comment by ghost** [comment]
I was having a difficult time coming up with what I might want to do for this project, but after listening to some of the examples and reading a few of the articles I have a much better understanding of what the project entails and how I want to approach it. I really liked the Cat in The Hat excerpt project; the sounds really helped create a mood. This really helped open my eyes up to what's possible when it comes to creating an audio story such as a soundscape. Music and sound are both extremely important when it comes to setting the mood and the tone of a piece and this excerpt project did it very well.

**Comment by benmiller314** [comment]
@tessasayers [asked](#issuecomment-454483783): 

> One question I have is, is it ok to have some white or quiet space? Should everything have some sound at all times, or does some quiet help to build the scene?

Great question, Tessa! In a word, yes, it's okay to have some quiet. One element to think about in all composition is where you're directing the audience's attention, and how – and one tool you have for directing attention is _contrast_. Just as a piece of music crafts phrases through crescendo (getting louder) and decrescendo (getting softer), a piece of soundwriting will likely do the same. And, as in music, a "grand pause" can provide a rather dramatic effect, drawing a lot of emphasis to whatever follows.

Even if you don't want to go full silence, because you don't want that drama, having all the foreground sounds drop out for a few seconds, while the background texture plays on, can give your narrative some breathing room.

**Comment by ZAR17** [comment]
I was able to get a few ideas for my own soundscape while listening to some of these. The cat in the hat example was pretty unique and I was able to get an understanding for how sounds can work together in different ways to portray a type of mood for the user. It showed me that it isn't necessarily what is being said, but rather how it's being used with other sounds. I'd like to use some of these techniques with my own project.
